name: Compare Mapping and Bump Version

on:
  workflow_dispatch:
  schedule:
    # Run once a month at midnight on the first day
    - cron: '0 0 1 * *'

jobs:
  compare-and-bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/*
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Compare with npm package
        id: compare
        run: |
          # Create temp directory and set paths
          TMP_DIR=$(mktemp -d)
          
          # Fetch package from npm and extract index.js
          PACKAGE_URL=$(npm view unicode-case-folding dist.tarball)
          curl -sL "$PACKAGE_URL" -o "$TMP_DIR/package.tgz"
          tar -xzf "$TMP_DIR/package.tgz" -C "$TMP_DIR"
          
          # Compare files and set output
          if diff -q "index.js" "$TMP_DIR/package/index.js"; then
            echo "result=same" >> $GITHUB_OUTPUT
          else
            echo "result=different" >> $GITHUB_OUTPUT
          fi

      - name: Bump patch version
        if: steps.compare.outputs.result == 'different'
        run: |
          # Configure Git
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Get current version and bump patch
          npm version patch -m "Bump version to %s"
          npm publish
    
          # Push changes back to the repository
          git push